Repository wardsquid/journal, pull requests merged in 2020-12, with the labels that each got.

#38 Implemented local push notifications with custom reminder
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/managers/LocalNotificationManager.dart
  lib/views/UserProfile.dart
  pubspec.yaml
Labels: frontend

#41 Initialized firestore document on user sign up; reminder time is updated and fetched from firestore; changed app id/name/package name globally
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/journal/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  lib/managers/Firebase.dart
  lib/managers/LocalNotificationManager.dart
  lib/managers/SignIn.dart
  lib/views/UserProfile.dart
  pubspec.yaml
  test/widget_test.dart
Labels: firestore, frontend

#50 added icon to be used for notifications and launcher; removed debug b…
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-v21/app_icon.png
  android/app/src/main/res/drawable/app_icon.png
  android/app/src/main/res/mipmap-hdpi/app_icon.png
  android/app/src/main/res/mipmap-mdpi/app_icon.png
  android/app/src/main/res/mipmap-xhdpi/app_icon.png
  android/app/src/main/res/mipmap-xxhdpi/app_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/app_icon.png
  android/settings_aar.gradle
  lib/main.dart
  lib/managers/LocalNotificationManager.dart
Labels: deployment, frontend

#53 Added internet permissions + signing key for release build
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
Labels: deployment

#68 Spotify Integration
  android/app/build.gradle
  android/settings.gradle
  android/spotify-app-remote/build.gradle
  android/spotify-app-remote/spotify-app-remote-release-0.7.1.aar
  android/spotify-auth/build.gradle
  android/spotify-auth/spotify-auth-release-1.2.3.aar
  lib/main.dart
  lib/managers/Spotify.dart
  lib/views/DiaryEntryView.dart
  lib/views/timeline/TimeLineView.dart
  pubspec.lock
  pubspec.yaml
Labels: auth, backend, firestore, frontend

#70 added speech init
  lib/views/DiaryEntryView.dart
Labels: frontend

#77 Can delete friend also from sharing_info, and cannot add friend who a…
  lib/views/UserProfile.dart
Labels: firestore, frontend

#78 Can remove spotify widget when tapping minus icon
  lib/views/DiaryEntryView.dart
Labels: frontend

#80 Swipe bug fix
  lib/main.dart
  lib/managers/Spotify.dart
  lib/views/DiaryEntryView.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#86 Commented out bottom bar and centered new entry action button
  lib/views/Calendar.dart
Labels: frontend

#100 Update README.md
  README.md
Labels: frontend

#107 Spotify player control in background implemented
  lib/managers/Spotify.dart
  lib/views/DiaryEntryView.dart
  lib/views/timeline/TimeLineView.dart
Labels: backend, frontend

#115 Adding our brand colors to every page; edited images and buttons for readability/accessibility
  assets/addphoto.jpg
  assets/place.jpg
  lib/views/Calendar.dart
  lib/views/DiaryEntryView.dart
  lib/views/UserProfile.dart
  lib/views/alerts/DiaryEntryAlerts.dart
  lib/views/timeline/TimeLineView.dart
Labels: frontend
